{
 "title": "Saga Orchestrée",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total des sagas",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "saga_total" }
   ]
  },
  {
   "title": "Sagas réussies",
   "type": "stat",
   "gridPos": { "x": 0, "y": 9, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "saga_success" }
   ]
  },
  {
   "title": "Sagas échouées",
   "type": "stat",
   "gridPos": { "x": 12, "y": 9, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "saga_fail" }
   ]
  },
  {
   "title": "Durée moyenne des sagas",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 18, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(saga_duration_seconds_sum[5m]) / rate(saga_duration_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Étapes OK",
   "type": "bargauge",
   "gridPos": { "x": 12, "y": 18, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(step) (saga_step_total{outcome=\"ok\"})"
    }
   ]
  },
  {
   "title": "Étapes KO",
   "type": "bargauge",
   "gridPos": { "x": 0, "y": 27, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(step) (saga_step_total{outcome=\"ko\"})"
    }
   ]
  },
  {
   "title": "Compensation - Suppression de vente",
   "type": "stat",
   "gridPos": { "x": 12, "y": 27, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "saga_step_total{step=\"COMP_DELETE_VENTE\"}"
    }
   ]
  },
  {
   "title": "Compensation - Réapprovisionnement",
   "type": "stat",
   "gridPos": { "x": 0, "y": 36, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "saga_step_total{step=\"COMP_REAPPRO\"}"
    }
   ]
  }
 ]
}