@startuml
title Diagramme de cas d'utilisation - Système de magasin

left to right direction

actor "Employé de magasin" as Empl
actor "Client" as Client
actor "Responsable logistique" as Resp
actor "Gestionnaire maison mère" as Gest

package "Système de magasin" {

  rectangle "Opérations de caisse" {
    usecase "Afficher les ventes" as UC_AfficherVente
    usecase "Rechercher un produit" as UC_RechercherProduit
    usecase "Enregistrer une vente" as UC_EnregistrerVente
    usecase "Annuler une vente" as UC_AnnulerVente
  }

  rectangle "Commerce" {
    usecase "Voir le panier" as UC_panier1
    usecase "Ajouter au panier" as UC_panier2
    usecase "Passer une commande" as UC_Commande
  }

  rectangle "Gestion magasin" {
    usecase "UC2: Consulter le stock central" as UC_ConsulterStock
    usecase "UC6: Approvisionner un magasin" as UC_Approvisionner
  }

  rectangle "Gestion centrale" {
    usecase "UC1: Générer un rapport consolidé" as UC_GenererRapport
    usecase "UC3: Tableau de bord de performance" as UC_TDB
    usecase "UC4: Mettre à jour un produit" as UC_MAJProduit
  }
}

' Relations
Empl --> UC_AfficherVente
Empl --> UC_RechercherProduit
Empl --> UC_EnregistrerVente
Empl --> UC_AnnulerVente

Client --> UC_Commande
Client --> UC_panier1
Client --> UC_panier2

Resp --> UC_ConsulterStock
Resp --> UC_Approvisionner

Gest --> UC_GenererRapport
Gest --> UC_TDB
Gest --> UC_MAJProduit

@enduml
